### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by makeworld-the-better-one** [makeworld-the-better-one/amfora#61]
- [x] A dynamically constructed (but possibly cached) feed viewer page, similar to the way CAPCOM and Spacewalk look
- [x] Automatic detection of feed files
	- Filenames: `atom.xml`, `feed.xml`, `*.rss`, `*.atom`, `feed.json`
	- Mimetypes: `application/atom+xml`, `application/rss+xml`, `application/json+feed`
	- [x] User will be prompted to add the feed
- [x] Some shortcut or button to add a URL at any time
	- If it's a valid feed it will be added as one, otherwise the page will be tracked
- [x] A way to edit the feed list and remove feeds
	- Maybe by visiting the page or any post URL and doing a delete shortcut?
- [x] Pagination

When should the feed view be regenerated?

- ~~On hard-reload of the feed viewer~~
- ~~On every X load of the feed viewer~~
- [x] At browser start
- [x] Every X minutes in a separate thread (30 mins by default)

**Comment by makeworld-the-better-one** [comment]
[gofeed](https://github.com/mmcdole/gofeed) for RSS and Atom feeds.

**Comment by makeworld-the-better-one** [comment]
The name for this needs to be unified before merging. Feeds are "subscribed" to, pages are "tracked", but also feeds are "tracked", etc. The name "feeds" is used throughout the code, but this is not representative due to the page tracking functionality.

Maybe just "Subscriptions"?
- subscribe to this feed
- subscribe to this page
- remove this subscription / unsubscribe
- refresh this subscription

**Comment by makeworld-the-better-one** [comment]
The "gemini feed format" (`gemini://gemini.circumlunar.space/docs/companion/subscription.gmi`) will not be supported initially. A separate issue will be opened, and it will likely be in a later release.

**Comment by makeworld-the-better-one** [comment]
Sometimes corrupted JSON files are being written. This is critical error that must be discovered and fixed before merging into master. Here is an example of the bottom of a corrupted file:

```json
    },
    "gemini://republic.circumlunar.space/users/xkp/gemlog/": {
      "hash": "24860ed36333d360817b5d35614fdd714266df360c54e35a2f1ac1ce7375d82a",
      "changed": "2020-11-24T18:34:49.418540845Z"
    }
  }
}
r.space/users/xkp/gemlog/": {
      "hash": "24860ed36333d360817b5d35614fdd714266df360c54e35a2f1ac1ce7375d82a",
      "changed": "2020-11-24T18:34:49.418540845Z"
    }
  }
}
.space/users/xkp/gemlog/": {
      "hash": "24860ed36333d360817b5d35614fdd714266df360c54e35a2f1ac1ce7375d82a",
      "changed": "2020-11-24T18:34:49.418540845Z"
    }
  }
}
```

The corrupted part begins on line 8. The entires don't have preceding quotes, and are also not inside the final closing brace on line 7. The hash and times are the same, suggesting this is maybe some sort of double write issue. Maybe mutexes are not being used in some function where they should be.

**Comment by makeworld-the-better-one** [comment]
Merged in 6d8e823! :smile:

**Comment by makeworld-the-better-one** [comment]
Other issues related to subscription: #144
